<?php
	/**
	 * @desc			Please edit this configuration file to set specific mimetypes for your fileoutput.
	 * @copyright		2007-2010 IPBWI development team
	 * @package			mimetypes
	 * @author			Matthias Reuter ($LastChangedBy: matthias $)
	 * @license			http://www.gnu.org/licenses/gpl-3.0.html GNU General Public License
	 * @version			$LastChangedDate: 2009-08-26 19:19:41 +0200 (Mi, 26 Aug 2009) $
	 * @since			2.0
	 * @web				http://ipbwi.com
	 */

	// application mimetypes
	$mimeTypes['dwg']		= 'application/acad';
	$mimeTypes['asn']		= 'application/astound';
	$mimeTypes['asd']		= 'application/astound';
	$mimeTypes['tsp']		= 'application/dsptype';
	$mimeTypes['dxf']		= 'application/dxf';
	$mimeTypes['spl']		= 'application/futuresplash';
	$mimeTypes['gz']		= 'application/gzip';
	$mimeTypes['ptlk']		= 'application/listenup';
	$mimeTypes['hqx']		= 'application/mac-binhex40';
	$mimeTypes['mbd']		= 'application/mbedlet';
	$mimeTypes['xla']		= 'application/msexcel';
	$mimeTypes['xls']		= 'application/msexcel';
	$mimeTypes['chm']		= 'application/mshelp';
	$mimeTypes['hlp']		= 'application/mshelp';
	$mimeTypes['pot']		= 'application/mspowerpoint';
	$mimeTypes['ppt']		= 'application/mspowerpoint';
	$mimeTypes['ppz']		= 'application/mspowerpoint';
	$mimeTypes['pps']		= 'application/mspowerpoint';
	$mimeTypes['dot']		= 'application/msword';
	$mimeTypes['doc']		= 'application/msword';
	$mimeTypes['dll']		= 'application/octet-stream';
	$mimeTypes['com']		= 'application/octet-stream';
	$mimeTypes['exe']		= 'application/octet-stream';
	$mimeTypes['oda']		= 'application/oda';
	$mimeTypes['pdf']		= 'application/pdf';
	$mimeTypes['ps']		= 'application/postscript';
	$mimeTypes['eps']		= 'application/postscript';
	$mimeTypes['ai']		= 'application/postscript';
	$mimeTypes['rtc']		= 'application/rtc';
	$mimeTypes['rtf']		= 'application/rtf';
	$mimeTypes['smp']		= 'application/studiom';
	$mimeTypes['tbk']		= 'application/toolbook';
	$mimeTypes['vmd']		= 'application/vocaltec-media-desc';
	$mimeTypes['vmf']		= 'application/vocaltec-media-file';
	$mimeTypes['xhtml']		= 'application/xhtml+xml';
	$mimeTypes['shtml']		= 'application/xhtml+xml';
	$mimeTypes['html']		= 'application/xhtml+xml';
	$mimeTypes['htm']		= 'application/xhtml+xml';
	$mimeTypes['xml']		= 'application/xml';
	$mimeTypes['bcpio']		= 'application/x-bcpio';
	$mimeTypes['z']			= 'application/x-compress';
	$mimeTypes['cpio']		= 'application/x-cpio';
	$mimeTypes['csh']		= 'application/x-csh';
	$mimeTypes['dxr']		= 'application/x-director';
	$mimeTypes['dir']		= 'application/x-director';
	$mimeTypes['dcr']		= 'application/x-director';
	$mimeTypes['dvi']		= 'application/x-dvi';
	$mimeTypes['evy']		= 'application/x-envoy';
	$mimeTypes['gtar']		= 'application/x-gtar';
	$mimeTypes['hdf']		= 'application/x-hdf';
	$mimeTypes['phtml']		= 'application/x-httpd-php';
	$mimeTypes['php']		= 'application/x-httpd-php';
	$mimeTypes['js']		= 'application/x-javascript';
	$mimeTypes['latex']		= 'application/x-latex';
	$mimeTypes['bin']		= 'application/x-macbinary';
	$mimeTypes['mif']		= 'application/x-mif';
	$mimeTypes['cdf']		= 'application/x-netcdf';
	$mimeTypes['nc']		= 'application/x-netcdf';
	$mimeTypes['nsc']		= 'application/x-nschat';
	$mimeTypes['sh']		= 'application/x-sh';
	$mimeTypes['shar']		= 'application/x-shar';
	$mimeTypes['cab']		= 'application/x-shockwave-flash';
	$mimeTypes['swf']		= 'application/x-shockwave-flash';
	$mimeTypes['sprite']	= 'application/x-sprite';
	$mimeTypes['spr']		= 'application/x-sprite';
	$mimeTypes['sit']		= 'application/x-stuffit';
	$mimeTypes['sca']		= 'application/x-supercard';
	$mimeTypes['sv4cpio']	= 'application/x-sv4cpio';
	$mimeTypes['sv4crc']	= 'application/x-sv4crc';
	$mimeTypes['tar']		= 'application/x-tar';
	$mimeTypes['tcl']		= 'application/x-tcl';
	$mimeTypes['tex']		= 'application/x-tex';
	$mimeTypes['texi']		= 'application/x-texinfo';
	$mimeTypes['texinfo']	= 'application/x-texinfo';
	$mimeTypes['roff']		= 'application/x-troff';
	$mimeTypes['tr']		= 'application/x-troff';
	$mimeTypes['t']			= 'application/x-troff';
	$mimeTypes['troff']		= 'application/x-troff-man';
	$mimeTypes['man']		= 'application/x-troff-man';
	$mimeTypes['me']		= 'application/x-troff-me';
	$mimeTypes['ms']		= 'application/x-troff-ms';
	$mimeTypes['ustar']		= 'application/x-ustar';
	$mimeTypes['src']		= 'application/x-wais-source';
	$mimeTypes['zip']		= 'application/zip';

	// audio mimetypes
	$mimeTypes['au']		= 'audio/basic';
	$mimeTypes['snd']		= 'audio/basic';
	$mimeTypes['es']		= 'audio/echospeech';
	$mimeTypes['tsi']		= 'audio/tsplayer';
	$mimeTypes['vox']		= 'audio/voxware';
	$mimeTypes['aif']		= 'audio/x-aiff';
	$mimeTypes['aiff']		= 'audio/x-aiff';
	$mimeTypes['aifc']		= 'audio/x-aiff';
	$mimeTypes['dus']		= 'audio/x-dspeeh';
	$mimeTypes['cht']		= 'audio/x-dspeeh';
	$mimeTypes['mid']		= 'audio/x-midi';
	$mimeTypes['midi']		= 'audio/x-midi';
	$mimeTypes['mp2']		= 'audio/x-mpeg';
	$mimeTypes['ram']		= 'audio/x-pn-realaudio';
	$mimeTypes['ra']		= 'audio/x-pn-realaudio';
	$mimeTypes['rpm']		= 'audio/x-pn-realaudio-plugin';
	$mimeTypes['stream']	= 'audio/x-qt-stream';
	$mimeTypes['wav']		= 'audio/x-wav';

	// drawing mimetypes
	$mimeTypes['dwf']		= 'drawing/x-dwf';

	// images mimetypes
	$mimeTypes['cod']		= 'image/cis-cod';
	$mimeTypes['ras']		= 'image/cmu-raster';
	$mimeTypes['fif']		= 'image/fif';
	$mimeTypes['gif']		= 'image/gif';
	$mimeTypes['ief']		= 'image/ief';
	$mimeTypes['jpg']		= 'image/jpeg';
	$mimeTypes['jpeg']		= 'image/jpeg';
	$mimeTypes['jpe']		= 'image/jpeg';
	$mimeTypes['png']		= 'image/png';
	$mimeTypes['tiff']		= 'image/tiff';
	$mimeTypes['tif']		= 'image/tiff';
	$mimeTypes['mcf']		= 'image/vasa';
	$mimeTypes['wbmp']		= 'image/vnd.wap.wbmp';
	$mimeTypes['fh4']		= 'image/x-freehand';
	$mimeTypes['fh5']		= 'image/x-freehand';
	$mimeTypes['fh6']		= 'image/x-freehand';
	$mimeTypes['fh7']		= 'image/x-freehand';
	$mimeTypes['fh8']		= 'image/x-freehand';
	$mimeTypes['fh9']		= 'image/x-freehand';
	$mimeTypes['fh10']		= 'image/x-freehand';
	$mimeTypes['fhc']		= 'image/x-freehand';
	$mimeTypes['pnm']		= 'image/x-portable-anymap';
	$mimeTypes['pbm']		= 'image/x-portable-bitmap';
	$mimeTypes['pgm']		= 'image/x-portable-graymap';
	$mimeTypes['ppm']		= 'image/x-portable-pixmap';
	$mimeTypes['rgb']		= 'image/x-rgb';
	$mimeTypes['xwd']		= 'image/x-windowdump';
	$mimeTypes['xbm']		= 'image/x-xbitmap';
	$mimeTypes['xpm']		= 'image/x-xpixmap';

	// text mimetypes
	$mimeTypes['csv']		= 'text/comma-separated-values';
	$mimeTypes['css']		= 'text/css';
	//$mimeTypes['htm']		= 'text/html';
	//$mimeTypes['html']	= 'text/html';
	//$mimeTypes['shtml']	= 'text/html';
	//$mimeTypes['js']		= 'text/javascript';
	$mimeTypes['txt']		= 'text/plain';
	$mimeTypes['rtx']		= 'text/richtext';
	//$mimeTypes['rtf']		= 'text/rtf';
	$mimeTypes['tsv']		= 'text/tab-separated-values';
	//$mimeTypes['xml']		= 'text/xml';
	$mimeTypes['etx']		= 'text/x-setext';
	$mimeTypes['sgm']		= 'text/x-sgml';
	$mimeTypes['sgml']		= 'text/x-sgml';
	$mimeTypes['talk']		= 'text/x-speech';
	$mimeTypes['spc']		= 'text/x-speech';

	// video mimetypes
	$mimeTypes['mpeg']		= 'video/mpeg';
	$mimeTypes['mpg']		= 'video/mpeg';
	$mimeTypes['mpe']		= 'video/mpeg';
	$mimeTypes['qt']		= 'video/quicktime';
	$mimeTypes['mov']		= 'video/quicktime';
	$mimeTypes['viv']		= 'video/vnd.vivo';
	$mimeTypes['vivo']		= 'video/vnd.vivo';
	$mimeTypes['avi']		= 'video/x-msvideo';
	$mimeTypes['movie']		= 'video/x-sgi-movie';
	$mimeTypes['vts']		= 'workbook/formulaone';
	$mimeTypes['vtts']		= 'workbook/formulaone';
?>